<?php
/**
 * See LICENSE.md for license details.
 */
?>
<?php /** @var Dhl_Versenden_Block_Checkout_Onepage_Shipping_Method_Service $this */
    $services = $this->getServices();
?>
<?php if (!$this->isShippingAddressDHLLocation() && $services->count() > 0): ?>
    <div id="checkout-dhlversenden-services" style="display: none;">
        <img
            src="<?php echo $this->escapeUrl($this->getSkinUrl('images/dhl_versenden/logo.png')) ?>"
            alt="<?php echo $this->escapeHtml($this->__('DHL Additional Services')) ?>"
            title="<?php echo $this->escapeHtml($this->__('DHL Additional Services')) ?>"
        />

        <?php if ($services->count() > 0): ?>
        <span>
            <?php echo $this->escapeHtml($this->__('DHL Preferred Delivery')) ?>:
            <?php echo $this->escapeHtml($this->__('Delivered just the way you want.')) ?>
        </span>

        <p>
            <?php echo $this->escapeHtml($this->__('You decide when and where you want to receive your parcels with the recipient services of DHL.')) ?><br/>
            <?php echo $this->escapeHtml($this->__('Please choose your preferred delivery option:')) ?>
        </p>
        <dl>
            <?php /** @var \Dhl\Versenden\ParcelDe\Service\Type\Generic $service */ ?>
            <?php foreach ($services as $service): ?>
                <?php
                    $headline = $this->getServiceHeadline($service->getCode());
                    $tooltip = $this->getServiceHint($service->getCode());
                ?>
                <dt class="service-<?php echo $this->escapeHtml($service->getFrontendInputType() . ' ' . $service::CODE) ?>">
                    <?php if ($headline !== ''): ?>
                        <?php
                            $headlineLabel = sprintf(
                                '<label class="service-headline" for="shipment_service_%s">%s</label>',
                                $this->escapeHtml($service->getCode()),
                                $this->escapeHtml($headline)
                            );
                        ?>
                        <?php /* @noEscape */ echo $this->injectTooltip($headlineLabel, $tooltip); ?>
                    <?php else: ?>
                        <?php echo $service->getSelectorHtml() ?>
                        <?php /* @noEscape */ echo $this->injectTooltip($service->getLabelHtml(), $tooltip); ?>
                    <?php endif; ?>
                </dt>
                <?php if ($headline === ''): ?>
                <dd>
                    <p><?php echo $this->getServiceFeeText($service->getCode()) ?></p>
                </dd>
                <?php endif; ?>
                <dd class="service-<?php echo $this->escapeHtml($service->getFrontendInputType() . ' ' . $service::CODE) ?>">
                    <?php if ($headline !== ''): ?>
                        <?php echo $service->getSelectorHtml() ?>
                        <?php /* @noEscape */ echo $service->getLabelHtml(); ?>
                    <?php endif; ?>
                    <?php if ($service->getCode() === \Dhl\Versenden\ParcelDe\Service\PreferredDay::CODE): ?>
                        <div>
                            <input type="radio"
                                   name="service_setting[<?php echo $this->escapeHtml($service->getCode()) ?>]"
                                   id="shipment_service_<?php echo $this->escapeHtml($service->getCode()) ?>_none"
                                   value="" checked="checked">
                            <label for="shipment_service_<?php echo $this->escapeHtml($service->getCode()) ?>_none"
                                   title="<?php echo $this->escapeHtml($this->helper('dhl_versenden/data')->__('no day')) ?>">
                                <span>-</span>
                                <span><?php echo $this->escapeHtml($this->helper('dhl_versenden/data')->__('no day')) ?></span>
                            </label>
                        </div>
                    <?php endif; ?>
                    <?php /* @noEscape */ echo $service->getValueHtml(); ?>
                </dd>
                <?php if ($headline !== ''): ?>
                <dd>
                    <p><?php echo $this->getServiceFeeText($service->getCode()) ?></p>
                </dd>
                <?php endif; ?>
            <?php endforeach; ?>
        </dl>
        <?php endif; ?>

        <?php if (!$this->isShippingAddressDHLLocation()): ?>

            <span>
                <?php
                $locationHint = $this->escapeHtml(
                    $this->__('Or choose a DHL Packstation or a branch as an alternative delivery address.')
                );
                if($this->isOnePageCheckout()): ?>
                    <a id="locationfinder-link" href="javascript:void(0)"><?php echo $locationHint; ?></a>
                <?php endif; ?>
            </span>

        <?php endif; ?>

        <script type="text/javascript">
            //<![CDATA[
            var serviceContainer = new DhlServiceContainer(
                'checkout-dhlversenden-services',
                '<?php /* @noEscape */  echo $this->getDhlMethods(); ?>'
            );
            serviceContainer.toggleServiceContainer();

            serviceContainer.registerMethodChange();
            serviceContainer.registerServiceDetailsChange();
            serviceContainer.registerCalendarChange();

            var locationLink = $('locationfinder-link');
            if (locationLink) {
                locationLink.observe('click', function () {
                    if (typeof checkout === 'undefined') {
                        return;
                    }

                    checkout.gotoSection('shipping');
                    document.getElementById('opc-shipping').scrollIntoView();

                    // Case: customer with saved addresses
                    var addressSelection = $$('#shipping-address-select option[value=""]').first();
                    if (addressSelection) {
                        addressSelection.selected = true;
                        $('shipping-new-address-form').show();
                    }

                    var locationFinderCheckbox = $('shipping:useLocationFinder');
                    if (locationFinderCheckbox) {
                        locationFinderCheckbox.checked = true;
                        locationFinder.showLocationData(locationFinderCheckbox.checked);
                    }
                });
            }

            var dhlPreferredLocation = $('shipment_service_preferredLocationDetails');
            var dhlPreferredNeighbour = $('shipment_service_preferredNeighbourDetails');
            if (dhlPreferredLocation && dhlPreferredNeighbour) {
                observeAndDisable(dhlPreferredLocation, dhlPreferredNeighbour);
            }

            var dhlPnCheckbox = $('shipment_service_preferredNeighbour');
            var dhlNndCheckbox = $('shipment_service_noNeighbourDelivery');
            if (dhlPnCheckbox && dhlNndCheckbox) {
                observeCheckboxExclusion(dhlPnCheckbox, dhlNndCheckbox, dhlPreferredNeighbour);
            }

            //]]>
        </script>
    </div>

<?php endif; ?>
