<?php
/**
 * See LICENSE.md for license details.
 */
?>
<?php
/** @var Dhl_Versenden_Block_Config_Service $this */
$services = $this->getServices();
?>
<?php if ($this->isAnyServiceSelected()): ?>
    <div class="dhl-services">
        <span class="service-label"><?php echo $this->escapeHtml($this->__('DHL Preferred Delivery')); ?></span>
        <ul>
            <?php foreach ($services as $key => $value): ?>
                <?php if ($value === null): ?>
                    <?php continue; ?>
                <?php endif; ?>
                <?php if ($key === 'preferredDay'): ?>
                    <li><?php echo $this->__($this->renderName($key)) . ': ' . $this->renderDate($value) ?></li>
                <?php elseif (in_array($key, ['parcelAnnouncement', 'noNeighbourDelivery', 'goGreen', 'closestDropPoint'], true)): ?>
                    <?php if ($value): ?>
                        <li><?php echo $this->__($this->renderName($key)) ?></li>
                    <?php endif; ?>
                <?php elseif ($key === 'preferredNeighbour'): ?>
                    <li><?php echo $this->__($this->renderName($key)) . ': ' . $value ?></li>
                <?php elseif ($key === 'preferredLocation'): ?>
                    <li><?php echo $this->__($this->renderName($key)) . ': ' . $value ?></li>
                <?php else: ?>
                    <?php continue; ?>
                <?php endif; ?>
            <?php endforeach; ?>
            <?php $feeText = $this->renderFeeText(); ?>
            <?php if ($feeText): ?>
            <li class="dhl-service-fee-hint"><span><?php echo $feeText ?></span></li>
            <?php endif; ?>
        </ul>
    </div>
<?php endif; ?>
