<?php
/**
 * See LICENSE.md for license details.
 */
?>
<?php /** @var Dhl_Versenden_Block_Adminhtml_Sales_Order_Shipment_Product $this */ ?>
<?php $products = $this->getProducts(); ?>
<?php if (is_array($products)): ?>
    <div id="packaging-dhlversenden-products">
        <div><?php echo $this->escapeHtml($this->__('Shipping Product')) ?></div>
        <ul class="product-list">
            <?php $isChecked = false; ?>
            <?php foreach ($products as $productCode => $productLabel): ?>
                <li>
                    <input type="radio"
                           class="radio"
                           name="shipping_product"
                           value="<?php echo $this->escapeHtml($productCode) ?>"
                           id="<?php echo $this->escapeHtml($productCode) ?>"
                           <?php if (!$isChecked): ?>
                           checked="checked"
                           <?php endif; ?>

                    />
                    <label for="<?php echo $this->escapeHtml($productCode) ?>"><?php echo $this->escapeHtml($productLabel) ?></label>
                </li>
            <?php $isChecked = true; ?>
            <?php endforeach; ?>
        </ul>
    </div>
<?php endif; ?>
