<?php
/** @var Dhl_Versenden_Block_Adminhtml_System_Config_MultiCheckbox $this */
$element = $this->getElement();
$inputName = $element->getName();
?>
<input type="hidden"
       value="<?php echo $this->escapeHtml($element->getData('value')); ?>"
       id="<?php echo $this->escapeHtml($element->getHtmlId()); ?>"
       name="<?php echo $this->escapeHtml($element->getName()); ?>"
>
<ul class="list-inline">
    <?php
    foreach ($element->getData('values') as $value => $label):
    ?>
    <li>
        <input type="checkbox"
               value="<?php echo $this->escapeHtml($value); ?>"
               name="<?php echo $this->escapeHtml($inputName); ?>"
               id="<?php echo $this->escapeHtml($inputName . '_' . $value); ?>"
            <?php echo in_array($value, $this->getSelectedValues($element), false) ? 'checked' : ''; ?>
        />
        <label for="<?php echo $this->escapeHtml($inputName . '_' . $value); ?>">
            <?php echo $this->escapeHtml($label); ?>
        </label>
    <?php endforeach; ?>
</ul>
<script>
    (function () {
        var checkboxes = document.querySelectorAll(
            "[type='checkbox'][name='<?php echo $this->escapeHtml($inputName);?>']"
        );
        var hidden = document.getElementById("<?php echo $this->escapeHtml($element->getHtmlId()); ?>");

        for (var i = 0; i < checkboxes.length; i++) {
            checkboxes[i].name = "";
            var values = hidden.value.split(",");
            if (values.indexOf(checkboxes[i].value) !== -1) {
                checkboxes[i].checked = true;
            }
            /** keep the hidden input value in sync with the checkboxes. **/
            checkboxes[i].addEventListener("change", function (event) {
                var checkbox = event.target;
                var values = hidden.value.split(",");
                var valueAlreadyIncluded = values.indexOf(checkbox.value) !== -1;
                if (checkbox.checked && !valueAlreadyIncluded) {
                    values.push(checkbox.value);
                } else if (!checkbox.checked && valueAlreadyIncluded) {
                    values.splice(values.indexOf(checkbox.value), 1)
                }
                hidden.value = values.filter(Boolean).join();
            });
        }
    })();
</script>
